### ISSUE TITLE
filestructure incomplete

### ISSUE THREAD

**Issue by Machuntox** [decouples/Unet#4]
Hey,
If i try to run the data.py file it doesnt work. All file paths are incomplete or dont exist. 

Example, when I try to run the data.py file:
Traceback (most recent call last):
  File "data.py", line 237, in <module>
    mydata.create_train_data()
  File "data.py", line 172, in create_train_data
    np.save(self.npy_path + '/imgs_train.npy', imgdatas)
  File "/home/stefanberger/anaconda3/envs/my_env/lib/python3.7/site-packages/numpy/lib/npyio.py", line 524, in save
    fid = open(file, "wb")
FileNotFoundError: [Errno 2] No such file or directory: '/npydata/imgs_train.npy'

Could you please upload the complete file-structure, so I can run your application?

**Comment by mxazz123** [comment]
see the csdn blog, and the file sturcture is there
